<?php
/** @var array $purchase @var array $items */
?>
<style>
    body{background:#f1f5f9;}
    .doc{max-width:800px;margin:24px auto;background:#fff;color:#111;border-radius:12px;padding:40px;box-shadow:0 10px 40px rgba(0,0,0,.1);}
    .doc h1{font-size:1.6rem;margin:0;}
    .doc table{width:100%;border-collapse:collapse;margin-top:20px;}
    .doc th{background:#f8fafc;text-align:left;padding:10px;font-size:.75rem;text-transform:uppercase;color:#64748b;border-bottom:2px solid #e2e8f0;}
    .doc td{padding:10px;border-bottom:1px solid #eef2f7;}
    .muted{color:#64748b;}
    .totals{margin-left:auto;width:280px;margin-top:16px;}
    .totals div{display:flex;justify-content:space-between;padding:5px 0;}
    .noprint{text-align:center;margin:16px;}
    @media print{.noprint{display:none;} body{background:#fff;} .doc{box-shadow:none;margin:0;}}
</style>
<div class="noprint">
    <button onclick="window.print()" style="padding:10px 22px;border:none;border-radius:10px;background:#dc2626;color:#fff;font-weight:600;cursor:pointer;">Print</button>
</div>
<div class="doc">
    <div style="display:flex;justify-content:space-between;align-items:flex-start;">
        <div><h1><?= e(setting('business_name', 'Nubia Inventory')) ?></h1><div class="muted"><?= e(setting('business_address', '')) ?></div><div class="muted"><?= e(setting('business_phone', '')) ?></div></div>
        <div style="text-align:right;"><h2 style="margin:0;">PURCHASE</h2><div class="muted"><?= e($purchase['reference']) ?></div><div class="muted"><?= date('F j, Y', strtotime($purchase['purchase_date'])) ?></div></div>
    </div>
    <hr style="margin:20px 0;border:none;border-top:1px solid #e2e8f0;">
    <div><strong>Supplier:</strong> <?= e($purchase['supplier_name'] ?? 'Cash Purchase') ?><br><span class="muted"><?= e($purchase['supplier_address'] ?? '') ?></span></div>
    <table>
        <thead><tr><th>Product</th><th>Qty</th><th>Unit Cost</th><th style="text-align:right;">Subtotal</th></tr></thead>
        <tbody>
        <?php foreach ($items as $it): ?>
            <tr><td><?= e($it['product_name']) ?><br><span class="muted" style="font-size:.8rem;"><?= e($it['sku']) ?></span></td>
                <td><?= rtrim(rtrim(number_format((float) $it['quantity'], 2), '0'), '.') ?></td><td><?= money($it['unit_cost']) ?></td><td style="text-align:right;"><?= money($it['subtotal']) ?></td></tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <div class="totals">
        <div><span class="muted">Subtotal</span><span><?= money($purchase['subtotal']) ?></span></div>
        <div><span class="muted">Discount</span><span>- <?= money($purchase['discount']) ?></span></div>
        <div><span class="muted">Tax</span><span><?= money($purchase['tax']) ?></span></div>
        <div><span class="muted">Shipping</span><span><?= money($purchase['shipping']) ?></span></div>
        <div style="border-top:2px solid #e2e8f0;font-weight:800;font-size:1.1rem;"><span>Total</span><span><?= money($purchase['total']) ?></span></div>
        <div><span class="muted">Paid</span><span><?= money($purchase['paid']) ?></span></div>
        <div><span class="muted">Due</span><span><?= money($purchase['due']) ?></span></div>
    </div>
    <p class="muted" style="margin-top:40px;text-align:center;font-size:.8rem;">Generated by Nubia Inventory · <?= date('Y-m-d H:i') ?></p>
</div>
