<?php

declare(strict_types=1);

/**
 * Canonical RBAC catalog and controller-action policy.
 *
 * Every authenticated business action must appear in `handlers`. The same
 * slugs drive the role editor, route enforcement, navigation and action UI.
 */
return [
    'catalog' => [
        'Main' => [
            'dashboard.view'            => 'View Dashboard',
            'dashboard.metrics'         => 'View Dashboard KPIs',
            'dashboard.charts'          => 'View Dashboard Charts',
            'dashboard.sales'           => 'View Dashboard Sales',
            'dashboard.profit'          => 'View Dashboard Profit',
            'dashboard.purchase'        => 'View Dashboard Purchase',
            'dashboard.expenses'        => 'View Dashboard Expenses',
            'dashboard.revenue'         => 'View Dashboard Revenue',
            'dashboard.due_collection'  => 'View Dashboard Due Collection',
            'dashboard.due_payment'     => 'View Dashboard Due Payment',
            'dashboard.stock_value'     => 'View Dashboard Stock Value',
            'pos.use'                   => 'Open POS Terminal',
            'pos.checkout'              => 'Complete POS Checkout',
            'direct.view'               => 'View Direct Buy & Sell',
            'direct.create'             => 'Create Direct Buy & Sell',
            'direct.invoice'            => 'Print Direct Buy & Sell Invoices',
        ],
        'Inventory' => [
            'products.view'           => 'View Products',
            'products.search'         => 'Search Products in Forms',
            'products.export'         => 'Export Products',
            'products.create'         => 'Create Products',
            'products.edit'           => 'Edit Products',
            'products.delete'         => 'Delete Products',
            'products.labels'         => 'Print Product Barcode / QR Labels',
            'products.serials.view'   => 'View / Search IMEI & Serial Numbers',
            'products.serials.manage' => 'Add, Edit & Delete IMEI / Serials',
            'costs.view'              => 'View Product Cost / Buying Prices',
            'products.wholesale.view' => 'View Product Wholesale Prices',
            'categories.view'         => 'View Categories',
            'categories.create'       => 'Create Categories',
            'categories.edit'         => 'Edit Categories',
            'categories.delete'       => 'Delete Categories',
            'brands.view'             => 'View Brands',
            'brands.create'           => 'Create Brands',
            'brands.edit'             => 'Edit Brands',
            'brands.delete'           => 'Delete Brands',
            'units.view'              => 'View Units',
            'units.create'            => 'Create Units',
            'units.edit'              => 'Edit Units',
            'units.delete'            => 'Delete Units',
            'warehouses.view'         => 'View Warehouses',
            'warehouses.create'       => 'Create Warehouses',
            'warehouses.edit'         => 'Edit Warehouses',
            'warehouses.delete'       => 'Delete Warehouses',
            'stock.view'              => 'View Stock Levels',
            'stock.history'           => 'View Stock Movement History',
            'stock.adjust'            => 'Adjust Stock',
            'stock.transfer'          => 'Transfer Stock',
        ],
        'Transactions' => [
            'sales.view'       => 'View Sales',
            'sales.create'     => 'Create Sales',
            'sales.exchange'   => 'Exchange Sold Items',
            'sales.payment'    => 'Collect Sale Payments',
            'sales.return'     => 'Return Sold Items',
            'sales.delete'     => 'Delete Sales',
            'sales.invoice'    => 'View / Print Sale Invoices',
            'purchases.view'   => 'View Purchases',
            'purchases.create' => 'Create Purchases',
            'purchases.payment'=> 'Record Purchase Payments',
            'purchases.return' => 'Return Purchased Items',
            'purchases.delete' => 'Delete Purchases',
            'purchases.invoice'=> 'View / Print Purchase Invoices',
            'quotations.view'  => 'View Quotations',
            'quotations.create'=> 'Create Quotations',
        ],
        'People' => [
            'customers.view'    => 'View Customers',
            'customers.create'  => 'Create Customers',
            'customers.edit'    => 'Edit Customers',
            'customers.delete'  => 'Delete Customers',
            'customers.payment' => 'Collect Customer Payments',
            'suppliers.view'    => 'View Suppliers',
            'suppliers.create'  => 'Create Suppliers',
            'suppliers.edit'    => 'Edit Suppliers',
            'suppliers.delete'  => 'Delete Suppliers',
            'suppliers.payment' => 'Pay Suppliers',
        ],
        'Finance' => [
            'profit.view'                => 'View Profit Figures',
            'sales_total.view'           => 'View Sales Totals',
            'revenue.view'               => 'View Revenue / Collected Amounts',
            'stock_value.view'           => 'View Stock Value',
            'dues.view'                  => 'View Dues / Receivable & Payable Summaries',
            'expenses.view'              => 'View Expenses',
            'expenses.create'            => 'Create Expenses',
            'expenses.edit'              => 'Edit Expenses',
            'expenses.delete'            => 'Delete Expenses',
            'expense_categories.view'    => 'View Expense Categories',
            'expense_categories.create'  => 'Create Expense Categories',
            'accounting.cash_book'       => 'View Cash Book',
            'accounting.bank_book'       => 'View Bank Book',
            'accounting.profit_loss'     => 'View Profit & Loss',
            'accounting.payables'        => 'View Payables',
            'accounting.receivables'     => 'View Receivables',
            'reports.view'               => 'Open Reports',
            'reports.sales'              => 'View Sales Report',
            'reports.purchases'          => 'View Purchase Report',
            'reports.profit'             => 'View Profit Report',
            'reports.expenses'           => 'View Expense Report',
            'reports.stock'              => 'View Stock Report',
            'reports.customers'          => 'View Customer Report',
            'reports.suppliers'          => 'View Supplier Report',
            'reports.export'             => 'Export / Print Reports',
        ],
        'Administration' => [
            'users.view'        => 'View Users',
            'users.create'      => 'Create Users',
            'users.edit'        => 'Edit Users',
            'users.delete'      => 'Delete Users',
            'users.assign_roles'=> 'Assign Roles to Users',
            'users.assign_super_admin' => 'Assign / Manage Super Admin Users',
            'users.assign_warehouses'  => 'Assign Users to Warehouses',
            'roles.view'        => 'View Roles',
            'roles.create'      => 'Create Roles',
            'roles.permissions' => 'Assign Role Permissions',
            'roles.delete'      => 'Delete Roles',
            'logs.view'         => 'View Activity Logs',
            'settings.view'     => 'View Settings',
            'settings.edit'     => 'Update Settings',
        ],
    ],

    'handlers' => [
        'DashboardController@index'             => 'dashboard.view',
        'DashboardController@chartData'         => 'dashboard.charts',

        'ProductController@index'               => 'products.view',
        'ProductController@show'                => 'products.view',
        'ProductController@export'              => 'products.export',
        'ProductController@create'              => 'products.create',
        'ProductController@store'               => 'products.create',
        'ProductController@edit'                => 'products.edit',
        'ProductController@update'              => 'products.edit',
        'ProductController@destroy'             => 'products.delete',
        'ProductController@apiSearch'            => 'products.search',
        'ProductController@apiSerials'           => 'products.serials.view',
        'ProductController@addSerials'           => 'products.serials.manage',
        'ProductController@updateSerial'         => 'products.serials.manage',
        'ProductController@destroySerial'        => 'products.serials.manage',
        'ProductController@barcode'              => 'products.labels',
        'ProductController@qrcode'               => 'products.labels',
        'ProductController@labels'               => 'products.labels',
        'ProductController@serialBarcode'        => 'products.labels',
        'ProductController@serialQrcode'         => 'products.labels',
        'ProductController@serialLabel'          => 'products.labels',

        'CategoryController@index'               => 'categories.view',
        'CategoryController@store'               => 'categories.create',
        'CategoryController@update'              => 'categories.edit',
        'CategoryController@destroy'             => 'categories.delete',
        'BrandController@index'                  => 'brands.view',
        'BrandController@store'                  => 'brands.create',
        'BrandController@update'                 => 'brands.edit',
        'BrandController@destroy'                => 'brands.delete',
        'UnitController@index'                   => 'units.view',
        'UnitController@store'                   => 'units.create',
        'UnitController@update'                  => 'units.edit',
        'UnitController@destroy'                 => 'units.delete',
        'WarehouseController@index'              => 'warehouses.view',
        'WarehouseController@store'              => 'warehouses.create',
        'WarehouseController@update'             => 'warehouses.edit',
        'WarehouseController@destroy'            => 'warehouses.delete',

        'StockController@index'                  => 'stock.view',
        'StockController@history'                => 'stock.history',
        'StockController@adjustmentForm'         => 'stock.adjust',
        'StockController@storeAdjustment'        => 'stock.adjust',
        'StockController@transferForm'           => 'stock.transfer',
        'StockController@storeTransfer'          => 'stock.transfer',

        'CustomerController@index'               => 'customers.view',
        'CustomerController@show'                => 'customers.view',
        'CustomerController@create'              => 'customers.create',
        'CustomerController@store'               => 'customers.create',
        'CustomerController@edit'                => 'customers.edit',
        'CustomerController@update'              => 'customers.edit',
        'CustomerController@destroy'             => 'customers.delete',
        'CustomerController@collectPayment'      => 'customers.payment',
        'SupplierController@index'               => 'suppliers.view',
        'SupplierController@show'                => 'suppliers.view',
        'SupplierController@create'              => 'suppliers.create',
        'SupplierController@store'               => 'suppliers.create',
        'SupplierController@edit'                => 'suppliers.edit',
        'SupplierController@update'              => 'suppliers.edit',
        'SupplierController@destroy'             => 'suppliers.delete',
        'SupplierController@makePayment'         => 'suppliers.payment',

        'PurchaseController@index'               => 'purchases.view',
        'PurchaseController@show'                => 'purchases.view',
        'PurchaseController@create'              => 'purchases.create',
        'PurchaseController@store'               => 'purchases.create',
        'PurchaseController@addPayment'          => 'purchases.payment',
        'PurchaseController@returnItems'         => 'purchases.return',
        'PurchaseController@destroy'             => 'purchases.delete',
        'PurchaseController@invoice'             => 'purchases.invoice',

        'PosController@index'                    => 'pos.use',
        'PosController@checkout'                 => 'pos.checkout',
        'SaleController@index'                   => 'sales.view',
        'SaleController@show'                    => 'sales.view',
        'SaleController@create'                  => 'sales.create',
        'SaleController@store'                   => 'sales.create',
        'SaleController@exchangeForm'            => 'sales.exchange',
        'SaleController@exchangeStore'           => 'sales.exchange',
        'SaleController@addPayment'              => 'sales.payment',
        'SaleController@returnItems'             => 'sales.return',
        'SaleController@destroy'                 => 'sales.delete',
        'SaleController@invoice'                 => 'sales.invoice',
        'SaleController@thermal'                 => 'sales.invoice',
        'SaleController@pdf'                     => 'sales.invoice',

        'QuotationController@index'              => 'quotations.view',
        'QuotationController@show'               => 'quotations.view',
        'QuotationController@create'             => 'quotations.create',
        'QuotationController@store'              => 'quotations.create',
        'DirectBuySellController@index'          => 'direct.view',
        'DirectBuySellController@show'           => 'direct.view',
        'DirectBuySellController@create'         => 'direct.create',
        'DirectBuySellController@store'          => 'direct.create',
        'DirectBuySellController@invoice'        => 'direct.invoice',

        'ExpenseController@index'                => 'expenses.view',
        'ExpenseController@store'                => 'expenses.create',
        'ExpenseController@update'               => 'expenses.edit',
        'ExpenseController@destroy'              => 'expenses.delete',
        'ExpenseController@categories'           => 'expense_categories.view',
        'ExpenseController@storeCategory'        => 'expense_categories.create',
        'AccountingController@cashBook'          => 'accounting.cash_book',
        'AccountingController@bankBook'          => 'accounting.bank_book',
        'AccountingController@profitLoss'        => 'accounting.profit_loss',
        'AccountingController@payables'          => 'accounting.payables',
        'AccountingController@receivables'       => 'accounting.receivables',
        'ReportController@index'                 => 'reports.view',
        'ReportController@sales'                 => 'reports.sales',
        'ReportController@purchases'             => 'reports.purchases',
        'ReportController@profit'                => 'reports.profit',
        'ReportController@expenses'              => 'reports.expenses',
        'ReportController@stock'                 => 'reports.stock',
        'ReportController@customers'             => 'reports.customers',
        'ReportController@suppliers'             => 'reports.suppliers',
        'ReportController@export'                => 'reports.export',

        'UserController@index'                   => 'users.view',
        'UserController@create'                  => 'users.create',
        'UserController@store'                   => 'users.create',
        'UserController@edit'                    => 'users.edit',
        'UserController@update'                  => 'users.edit',
        'UserController@destroy'                 => 'users.delete',
        'RoleController@index'                   => 'roles.view',
        'RoleController@store'                   => 'roles.create',
        'RoleController@permissions'             => 'roles.permissions',
        'RoleController@savePermissions'         => 'roles.permissions',
        'RoleController@destroy'                 => 'roles.delete',
        'ActivityLogController@index'            => 'logs.view',
        'SettingController@index'                => 'settings.view',
        'SettingController@update'               => 'settings.edit',
    ],

    // Self-service endpoints intentionally remain available to every signed-in
    // user: profile, own password, theme, notifications, logout and PWA assets.
    'self_service_handlers' => [
        'ProfileController@edit',
        'ProfileController@update',
        'ProfileController@changePassword',
        'SettingController@saveTheme',
        'NotificationController@open',
        'NotificationController@read',
        'NotificationController@readAll',
        'SearchController@global',
    ],
];
